#定义端口
server:
  port: 8088
  servlet:
    context-path: /sell
#定义数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seller?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
#属性为null的返回值不展示
  jackson:
    default-property-inclusion: non_null
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
#日志
logging:
  config: classpath:logback-spring.xml
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.godwin.dataobject
  configuration:
    map-underscore-to-camel-case: true
# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql